apiVersion: v1
kind: ConfigMap
metadata: 
  name: myconfigmap
data:
  DBSERVERNAME: karthikdbserver
  DBNAME: karthikdb
  DBUSERNAME: karthikeyan
---
apiVersion: v1
kind: Service
metadata:
  name: mymvcapp-svc
spec:
  selector: 
    app: mvcwebapp
  type: NodePort
  ports:
    - name: http
      port: 3000              # cluster IP port
      targetPort: 5000    #container port
      nodePort: 30000   # host port
---
apiVersion: v1
kind: Pod
metadata: 
  name: mymvcapp-pod
  labels:
    app: mvcwebapp
spec:
  containers:
    - name: mymvcapp-container
      image:  karthik2153acr.azurecr.io/mymvcapp:v1
      ports:
        - containerPort: 5000
      envFrom:
        - configMapRef:
            name: myconfigmap
        - secretRef:
            name: mysecret
  imagePullSecrets:
    - name: acrsecret