apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: dotnetapp-container
          image: karthik1409docker/demodotnetcoreapps:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-svc
spec:
  selector: 
    tier: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 5000
      nodePort: 30000
